<a href="https://colab.research.google.com/github/sudeepbhagat11/Word-Embedding-Technique/blob/main/Word_Embedded_Technique.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word Embedding Techniques using Embedding Layer in Keras

1.   List item
2.   List item




In [5]:
!pip install tensorflow==2.12.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.9/585.9 MB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 6.6 MB/s eta 0:00:00
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.15.0
    Uninstalling tensorflow-estimator-2.15.0:
      Successfully uninstalled tensorflow-estimator-2.15.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2
  Attempting uninstall: keras
    Found existing installation: keras 2.15.0
    Uninstalling keras-2.15.0:
      Successfully uninstalled keras-2.15.0
  Attempting uninstall: gast
    Found existing installation: gast 0.6.0
    Uninstalling gast-0.

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=500

### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[148, 272, 65, 52], [148, 272, 65, 226], [148, 244, 65, 427], [248, 103, 90, 6, 416], [248, 103, 90, 6, 147], [281, 148, 193, 65, 250], [291, 426, 151, 6]]


## Word Embedding Representation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 148 272  65  52]
 [  0   0   0   0 148 272  65 226]
 [  0   0   0   0 148 244  65 427]
 [  0   0   0 248 103  90   6 416]
 [  0   0   0 248 103  90   6 147]
 [  0   0   0 281 148 193  65 250]
 [  0   0   0   0 291 426 151   6]]


In [9]:
## 10 feature dimesnions
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 148, 272,  65,  52], dtype=int32)

In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 106ms/step


array([[ 0.00481602, -0.01161975,  0.01807276,  0.0190967 , -0.02044044,
         0.0363566 , -0.02961726,  0.04091102,  0.03531969,  0.03817353],
       [ 0.00481602, -0.01161975,  0.01807276,  0.0190967 , -0.02044044,
         0.0363566 , -0.02961726,  0.04091102,  0.03531969,  0.03817353],
       [ 0.00481602, -0.01161975,  0.01807276,  0.0190967 , -0.02044044,
         0.0363566 , -0.02961726,  0.04091102,  0.03531969,  0.03817353],
       [ 0.00481602, -0.01161975,  0.01807276,  0.0190967 , -0.02044044,
         0.0363566 , -0.02961726,  0.04091102,  0.03531969,  0.03817353],
       [ 0.03679992,  0.0208911 ,  0.03093903,  0.04492842,  0.00933522,
        -0.01965214,  0.0260323 ,  0.01387313, -0.04132755,  0.0017639 ],
       [ 0.0361214 ,  0.04680895,  0.01263603,  0.00080438, -0.01023686,
        -0.04556028,  0.03555072, -0.03206185,  0.0018761 , -0.03426921],
       [-0.00159112, -0.02620993,  0.02301918, -0.04178981, -0.02576407,
         0.03824308,  0.0312815 ,  0.02936018

In [14]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 48ms/step
[[[ 0.00481602 -0.01161975  0.01807276  0.0190967  -0.02044044
    0.0363566  -0.02961726  0.04091102  0.03531969  0.03817353]
  [ 0.00481602 -0.01161975  0.01807276  0.0190967  -0.02044044
    0.0363566  -0.02961726  0.04091102  0.03531969  0.03817353]
  [ 0.00481602 -0.01161975  0.01807276  0.0190967  -0.02044044
    0.0363566  -0.02961726  0.04091102  0.03531969  0.03817353]
  [ 0.00481602 -0.01161975  0.01807276  0.0190967  -0.02044044
    0.0363566  -0.02961726  0.04091102  0.03531969  0.03817353]
  [ 0.03679992  0.0208911   0.03093903  0.04492842  0.00933522
   -0.01965214  0.0260323   0.01387313 -0.04132755  0.0017639 ]
  [ 0.0361214   0.04680895  0.01263603  0.00080438 -0.01023686
   -0.04556028  0.03555072 -0.03206185  0.0018761  -0.03426921]
  [-0.00159112 -0.02620993  0.02301918 -0.04178981 -0.02576407
    0.03824308  0.0312815   0.02936018 -0.01941633  0.0291913 ]
  [ 0.02428068  0.03624872  0.00059055 -0.00820402 -0.00156

In [15]:
embedded_docs[0]

array([  0,   0,   0,   0, 148, 272,  65,  52], dtype=int32)

In [16]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 24ms/step
[[ 0.00481602 -0.01161975  0.01807276  0.0190967  -0.02044044  0.0363566
  -0.02961726  0.04091102  0.03531969  0.03817353]
 [ 0.00481602 -0.01161975  0.01807276  0.0190967  -0.02044044  0.0363566
  -0.02961726  0.04091102  0.03531969  0.03817353]
 [ 0.00481602 -0.01161975  0.01807276  0.0190967  -0.02044044  0.0363566
  -0.02961726  0.04091102  0.03531969  0.03817353]
 [ 0.00481602 -0.01161975  0.01807276  0.0190967  -0.02044044  0.0363566
  -0.02961726  0.04091102  0.03531969  0.03817353]
 [ 0.03679992  0.0208911   0.03093903  0.04492842  0.00933522 -0.01965214
   0.0260323   0.01387313 -0.04132755  0.0017639 ]
 [ 0.0361214   0.04680895  0.01263603  0.00080438 -0.01023686 -0.04556028
   0.03555072 -0.03206185  0.0018761  -0.03426921]
 [-0.00159112 -0.02620993  0.02301918 -0.04178981 -0.02576407  0.03824308
   0.0312815   0.02936018 -0.01941633  0.0291913 ]
 [ 0.02428068  0.03624872  0.00059055 -0.00820402 -0.00156416  0.04890766
   